language: node_js
node_js:
  - "8"
script:
 - echo "Deploy To Firebase CI"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project angular-cn-docs --token $FIREBASE_TOKEN
