language: node_js
node_js:
  - "12"
script:
 - echo "Deploy To Firebase CI"
install:
  - npm install -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: angular-cn-docs
after_success:
  - firebase deploy --project angular-cn-docs --token $FIREBASE_TOKEN
